name: Chorewheel
options:
  bundleIdPrefix: com.shimondeitel.chorewheel
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Chorewheel:
    type: application
    platform: iOS
    sources:
      - path: Chorewheel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.chorewheel
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Chorewheel/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  ChorewheelTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ChorewheelTests
      - path: Chorewheel.storekit
    dependencies:
      - target: Chorewheel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.chorewheel.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  ChorewheelUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ChorewheelUITests
    dependencies:
      - target: Chorewheel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.chorewheel.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Chorewheel:
    build:
      targets:
        Chorewheel: all
        ChorewheelTests: [test]
        ChorewheelUITests: [test]
    test:
      targets:
        - ChorewheelTests
        - ChorewheelUITests
